flowchart TD
    A[今月のファシリテーターが今月の月次ふりかえりのワークを実施]
    B[今月のファシリテーターがページと WB を準備]
    C[来月の月次ふりかえりワークまでに非同期の個人ワークを実施]
    D[来月の月次ふりかえりのファシリテーターが来月の打ち合わせワークを準備]
    E[繰り返し]

    A --> B
    B --> C
    C --> D
    D --> E
    E -.-> A
