gantt
  title プロジェクト工程ガントチャート
  dateFormat  YYYY-MM-DD
  section 工程
  計画：5 : plan, 2025-07-09, 5d
  調査：25 : research, after plan, 25d
  要求分析：10 : analysis, after research, 10d
  要件定義：15 : definition, after analysis, 15d
  レビュー：1 : review, after definition, 1d
